version: '3.8'

services:
  # قاعدة بيانات PostgreSQL للتطوير
  postgres:
    image: postgres:15-alpine
    container_name: estate_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: estate_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5433:5432"
    networks:
      - estate_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d estate_db_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # تطبيق Next.js للتطوير
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: estate_app_dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/estate_db_dev?schema=public
      - JWT_SECRET=your_super_secret_jwt_key_2024
      - ADMIN_KEY=ADMIN_SECRET_2024
      - NEXT_PUBLIC_ADMIN_KEY=ADMIN_SECRET_2024
      - NEXT_PUBLIC_ADMIN_URL=admin2024
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - app_dev_data:/app/data
      - app_dev_var:/app/var
    networks:
      - estate_dev_network
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local
  app_dev_data:
    driver: local
  app_dev_var:
    driver: local

networks:
  estate_dev_network:
    driver: bridge
