services:
  # قاعدة بيانات PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: estate_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: estate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - estate_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d estate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # تطبيق Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estate_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/estate_db?schema=public
      - JWT_SECRET=your_super_secret_jwt_key_2024
      - ADMIN_KEY=ADMIN_SECRET_2024
      - NEXT_PUBLIC_ADMIN_KEY=ADMIN_SECRET_2024
      - NEXT_PUBLIC_ADMIN_URL=admin2024
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - app_data:/app/data
      - app_var:/app/var
    networks:
      - estate_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis للتخزين المؤقت (اختياري)
  redis:
    image: redis:7-alpine
    container_name: estate_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - estate_network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
    driver: local
  app_data:
    driver: local
  app_var:
    driver: local
  redis_data:
    driver: local

networks:
  estate_network:
    driver: bridge
