# Generated by Django 5.2.6 on 2025-09-17 08:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('action', models.CharField(max_length=100, verbose_name='الإجراء')),
                ('entity_type', models.CharField(max_length=100, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(max_length=100, verbose_name='معرف الكيان')),
                ('old_values', models.TextField(blank=True, null=True, verbose_name='القيم القديمة')),
                ('new_values', models.TextField(blank=True, null=True, verbose_name='القيم الجديدة')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف المستخدم')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='وكيل المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'سمسار',
                'verbose_name_plural': 'السماسرة',
            },
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'قيمة مفتاح',
                'verbose_name_plural': 'قيم المفاتيح',
            },
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم المجموعة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مجموعة شركاء',
                'verbose_name_plural': 'مجموعات الشركاء',
            },
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم الخزنة')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد')),
            ],
            options={
                'verbose_name': 'خزنة',
                'verbose_name_plural': 'الخزائن',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'إعداد',
                'verbose_name_plural': 'الإعدادات',
            },
        ),
        migrations.CreateModel(
            name='BrokerDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('due_date', models.DateTimeField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('معلق', 'معلق'), ('مدفوع', 'مدفوع'), ('متأخر', 'متأخر')], default='معلق', max_length=50, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_dues', to='accounting_app.broker', verbose_name='السمسار')),
            ],
            options={
                'verbose_name': 'دين سمسار',
                'verbose_name_plural': 'ديون السماسرة',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم القومي')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('status', models.CharField(default='نشط', max_length=50, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'indexes': [models.Index(fields=['status', 'deleted_at'], name='accounting__status_16bfa0_idx'), models.Index(fields=['name'], name='accounting__name_2d7e8a_idx'), models.Index(fields=['phone'], name='accounting__phone_11d206_idx'), models.Index(fields=['created_at'], name='accounting__created_f707ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'indexes': [models.Index(fields=['name'], name='accounting__name_680172_idx'), models.Index(fields=['phone'], name='accounting__phone_eeb814_idx'), models.Index(fields=['deleted_at'], name='accounting__deleted_5b92b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('due_date', models.DateTimeField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('معلق', 'معلق'), ('مدفوع', 'مدفوع'), ('متأخر', 'متأخر')], default='معلق', max_length=50, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_debts', to='accounting_app.partner', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'دين شريك',
                'verbose_name_plural': 'ديون الشركاء',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('from_safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='accounting_app.safe', verbose_name='من خزنة')),
                ('to_safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='accounting_app.safe', verbose_name='إلى خزنة')),
            ],
            options={
                'verbose_name': 'تحويل',
                'verbose_name_plural': 'التحويلات',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='كود الوحدة')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الوحدة')),
                ('unit_type', models.CharField(choices=[('سكني', 'سكني'), ('تجاري', 'تجاري'), ('إداري', 'إداري'), ('صناعي', 'صناعي')], default='سكني', max_length=50, verbose_name='نوع الوحدة')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='المساحة')),
                ('floor', models.CharField(blank=True, max_length=50, null=True, verbose_name='الطابق')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='المبنى')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('متاحة', 'متاحة'), ('محجوزة', 'محجوزة'), ('مباعة', 'مباعة')], default='متاحة', max_length=50, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'indexes': [models.Index(fields=['status', 'deleted_at'], name='accounting__status_273326_idx'), models.Index(fields=['unit_type', 'deleted_at'], name='accounting__unit_ty_80db7b_idx'), models.Index(fields=['total_price'], name='accounting__total_p_eb4edc_idx'), models.Index(fields=['created_at'], name='accounting__created_68fd31_idx'), models.Index(fields=['code'], name='accounting__code_946aab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('type', models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند دفع')], max_length=50, verbose_name='نوع السند')),
                ('date', models.DateTimeField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('payer', models.CharField(blank=True, max_length=255, null=True, verbose_name='المدفوع له')),
                ('beneficiary', models.CharField(blank=True, max_length=255, null=True, verbose_name='المستفيد')),
                ('linked_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع المرتبط')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='accounting_app.safe', verbose_name='الخزنة')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'السندات',
            },
        ),
        migrations.CreateModel(
            name='PartnerGroupPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='النسبة المئوية')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_groups', to='accounting_app.partner', verbose_name='الشريك')),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='accounting_app.partnergroup', verbose_name='مجموعة الشركاء')),
            ],
            options={
                'verbose_name': 'شريك مجموعة',
                'verbose_name_plural': 'شركاء المجموعات',
                'unique_together': {('partner_group', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('due_date', models.DateTimeField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('معلق', 'معلق'), ('مدفوع', 'مدفوع'), ('متأخر', 'متأخر')], default='معلق', max_length=50, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='accounting_app.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'الأقساط',
                'indexes': [models.Index(fields=['unit', 'deleted_at'], name='accounting__unit_id_0a79f3_idx'), models.Index(fields=['status', 'deleted_at'], name='accounting__status_19377c_idx'), models.Index(fields=['due_date'], name='accounting__due_dat_848377_idx'), models.Index(fields=['amount'], name='accounting__amount_cde18e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('start', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر الإجمالي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ الخصم')),
                ('broker_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم السمسار')),
                ('broker_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة العمولة')),
                ('broker_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ العمولة')),
                ('commission_safe_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='خزنة العمولة')),
                ('down_payment_safe_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='خزنة المقدم')),
                ('maintenance_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='وديعة الصيانة')),
                ('installment_type', models.CharField(choices=[('شهري', 'شهري'), ('ربع سنوي', 'ربع سنوي'), ('نصف سنوي', 'نصف سنوي'), ('سنوي', 'سنوي')], default='شهري', max_length=50, verbose_name='نوع الأقساط')),
                ('installment_count', models.PositiveIntegerField(default=0, verbose_name='عدد الأقساط')),
                ('extra_annual', models.PositiveIntegerField(default=0, verbose_name='الدفعات السنوية الإضافية')),
                ('annual_payment_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة الدفعة السنوية')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المقدم')),
                ('payment_type', models.CharField(choices=[('installment', 'تقسيط'), ('cash', 'كاش')], default='installment', max_length=50, verbose_name='نوع الدفع')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounting_app.customer', verbose_name='العميل')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounting_app.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'indexes': [models.Index(fields=['unit', 'deleted_at'], name='accounting__unit_id_ccc887_idx'), models.Index(fields=['customer', 'deleted_at'], name='accounting__custome_043725_idx'), models.Index(fields=['start'], name='accounting__start_e8d51c_idx'), models.Index(fields=['total_price'], name='accounting__total_p_0d6fbf_idx'), models.Index(fields=['created_at'], name='accounting__created_42ba90_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnitPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='النسبة المئوية')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_partners', to='accounting_app.partner', verbose_name='الشريك')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_partners', to='accounting_app.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'شريك وحدة',
                'verbose_name_plural': 'شركاء الوحدات',
                'indexes': [models.Index(fields=['unit', 'deleted_at'], name='accounting__unit_id_8c51b0_idx'), models.Index(fields=['partner', 'deleted_at'], name='accounting__partner_0df48f_idx')],
                'unique_together': {('unit', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='UnitPartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('partner_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_partner_groups', to='accounting_app.partnergroup', verbose_name='مجموعة الشركاء')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_partner_groups', to='accounting_app.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة مجموعة شركاء',
                'verbose_name_plural': 'وحدات مجموعات الشركاء',
                'unique_together': {('unit', 'partner_group')},
            },
        ),
    ]
