[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PRISMA_GENERATE_DATAPROXY = "true"
  DATABASE_URL = "postgresql://placeholder:placeholder@placeholder:5432/placeholder"
  DATABASE_PROVIDER = "postgresql"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_CONFIG_SAVE_EXACT = "true"
  NPM_CONFIG_PACKAGE_LOCK = "true"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"

# Edge functions for API routes
[[edge_functions]]
  function = "api"
  path = "/api/*"